name: publishNetlify
on:
  push:
    branches:    
      - main
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - run : sudo apt-get --assume-yes install asciidoctor 
    - run : sudo apt-get --assume-yes install linkchecker 
    - run : make all && linkchecker --check-extern ./dist
    - name: Publish
      uses : netlify/actions/cli@master
      with:
        args: deploy --prod --dir=./dist/
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}